apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fqciw3tau-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fqciw3tau-python 
  name: fqciw3tau-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fqciw3tau-python 
